[tool.typeo.scripts.train]
ifos = ["H1", "L1"]

# optimization args
batch_size = 384
max_epochs = 200
max_lr = 0.000585
lr_ramp_epochs = 23
weight_decay = 0.0


snr_thresh = 4
max_min_snr = 12
max_snr = 100
snr_alpha = 3
snr_decay_steps = 989


# data args
sample_rate = 2048 
kernel_length = 1.5
psd_length = 8
fduration = 1
highpass = 32
fftlength = 2

# augmentation args
trigger_distance = -0.75
waveform_prob = 0.277
swap_frac = 0.014
mute_frac = 0.055

# validation args
valid_frac = 0.25
valid_stride = 0.5
max_fpr = 1e-3
valid_livetime = 57600  # 16 hours of background
early_stop = 200
checkpoint_every = 3

# misc args
device = "cuda"
verbose = true
use_amp = true
