name: bbhnet-omicron-production
channels:
  - conda-forge
dependencies:
  - python=3.9
  - python-ldas-tools-framecpp==2.6.14
  - python-nds2-client
  - python-ligo-lw
  - pyomicron
  - omicron>=4.0.0
  - dqsegdb2
  - uproot
