name: aframe-datagen
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - libgcc
  - h5py
  # torch dependencies
  - cpuonly
  - pytorch>=1.10,<2.0
  # general GW dependenceis
  - krb5
  - gwpy>=2.1,<3.0
  - lalsuite>=7.19
  # frame file I/O dependencies
  - python-ldas-tools-framecpp<3.0.0
  - python-nds2-client
  # omicron dependencies
  - python-ligo-lw
  - omicron>=4.0.0
  - uproot
  # pip requirements
  - pip
  - poetry
  # - pip:
  #   - torchtyping>=0.1 --install-option="--no-deps"
  #   - git+https://github.com/ml4gw/mldatafind --install-option="--no-deps"
  #   - -e ../../ml4gw --install-option="--no-deps --no-build-isolation"
  #   - -e ../utils --install-option="--no-deps --no-build-isolation"
