[tool.pinto]
steps = [
    "data_gen:launch-datagen",
    "training:launch-training",
    "exporting:launch-export:resnet",
    "inference:launch-inference",
]


[tool.typeo.base]

Tb = 86400 #5184000  # 60 days of background
shifts = [0, 1]

inference_psd_length = 64
training_psd_length = 8
inference_sampling_rate = 16
inference_batch_size = 128
hopeless_snr_thresh = 4
sample_rate = 2048
ifos = ["H1", "L1"]
basedir = "${INTERVAL_DIR}"
highpass = 32
fduration = 1
kernel_length = 1.5
resnet = {layers = [3, 4, 6, 3], norm_groups = 16} 

[tool.typeo.scripts.launch-datagen]
basedir = "${base.basedir}"

test_stop = 1244035783
intervals = [1, 2, 4, 12, 24, 32] # number of weeks
channel = "DCS-CALIB_STRAIN_CLEAN_C01"
sample_rate = "${base.sample_rate}"
ifos = "${base.ifos}"
state_flag = "DCS-ANALYSIS_READY_C01:1"
min_segment_length = 1024
max_segment_length = 20000
duration = 86400 #604800 # one week of data

Tb = "${base.Tb}"  # 60 days of background
shifts = "${base.shifts}"
spacing = 48
buffer = 16
prior = "aframe.priors.priors.end_o3_ratesandpops"
waveform_duration = 4
reference_frequency = 50
minimum_frequency = 20
waveform_approximant = "IMRPhenomPv2"
highpass = "${base.highpass}"
snr_threshold = 4
psd_length = "${base.inference_psd_length}"

num_signals = 1000

# condor args
accounting_group_user = "${LIGO_USERNAME}"
accounting_group = "${LIGO_GROUP}"
verbose = true

[tool.typeo.scripts.launch-training]
basedir = "${base.basedir}"
gpus = [2, 3, 4, 5, 6, 7, 8]

[tool.typeo.scripts.train]

# optimization args
batch_size = 384
max_epochs = 2
max_lr = 0.000585
lr_ramp_epochs = 1
weight_decay = 0.0


snr_thresh = "${base.hopeless_snr_thresh}"
max_min_snr = 12
max_snr = 100
snr_alpha = 3
snr_decay_steps = 989


# data args
ifos = "${base.ifos}"
sample_rate = "${base.sample_rate}"
kernel_length = "${base.kernel_length}"
fduration = "${base.fduration}"
highpass = "${base.highpass}"
psd_length = "${base.training_psd_length}"
fftlength = 2

# augmentation args
trigger_distance = -0.75
waveform_prob = 0.277
swap_frac = 0.014
mute_frac = 0.055

# validation args
valid_frac = 0.25
valid_stride = 0.5
max_fpr = 1e-3
valid_livetime = 57600  # 16 hours of background
early_stop = 200
checkpoint_every = 3

# misc args
device = "cuda"
verbose = true
use_amp = true

commands.resnet = "${base.resnet}"


[tool.typeo.scripts.launch-export]
basedir = "${base.basedir}"

# input-output mapping info
num_ifos = 2 
inference_sampling_rate = "${base.inference_sampling_rate}"
sample_rate = "${base.sample_rate}"
kernel_length = 1.5 
batch_size = "${base.inference_batch_size}"
fduration = "${base.fduration}"
highpass = "${base.highpass}"
psd_length = "${base.inference_psd_length}" 

# repo/triton parameters
aframe_instances = 6
streams_per_gpu = 3 
platform = "tensorrt_plan"
verbose = false
clean = true

# arch parameters
commands.resnet = "${base.resnet}"


[tool.typeo.scripts.launch-inference]
basedir = "${base.basedir}"
original_model_repo_dir = "/home/ethan.marx/aframe/paper/best_o3_model/iteration_1/model_repo/"
image = "hermes/tritonserver:22.12"
model_name = "aframe-stream"

accounting_group_user = "${LIGO_USERNAME}"
accounting_group = "${LIGO_GROUP}"
Tb = "${base.Tb}"
shifts = "${base.shifts}"
sample_rate = "${base.sample_rate}"
inference_sampling_rate = 16
ifos = "${base.ifos}"
batch_size = "${base.inference_batch_size}" 
integration_window_length = 1
cluster_window_length = 8
psd_length = "${base.inference_psd_length}" 
fduration = 1
throughput = 320
chunk_size = 4096
sequence_id = 1001

verbose = true
