[tool.pinto]
steps = [
    "data_gen:launch-datagen",
    #"infer:launch-infer",
]

[tool.typeo.scripts.launch-datagen]
datadir = "${DATA_DIR}"

test_stop = 1244035783
intervals = [1, 2] #4, 12, 24, 32, 48] # number of weeks
channel = "DCS-CALIB_STRAIN_CLEAN_C01"
sample_rate = 2048
ifos = ["H1", "L1"]
state_flag = "DCS-ANALYSIS_READY_C01:1"
min_segment_length = 1024
max_segment_length = 20000
duration = 604800 # one week of data

Tb = 5184000  # 60 days of background
shifts = [0, 1]
spacing = 48
buffer = 16
prior = "aframe.priors.priors.end_o3_ratesandpops"
waveform_duration = 4
reference_frequency = 50
minimum_frequency = 20
waveform_approximant = "IMRPhenomPv2"
highpass = 32
snr_threshold = 4
psd_length = 16

# condor args
accounting_group_user = "${LIGO_USERNAME}"
accounting_group = "${LIGO_GROUP}"
verbose = true
