name: aframe-longevity
channels:
  - conda-forge
dependencies:
  - python=3.9
  - libgcc
  - gwpy
  - astropy
  - matplotlib
  # frame file I/O dependencies
  - python-ldas-tools-framecpp
  - python-nds2-client
  # injection dependencies
  - bilby
  - lalsuite
